### ISSUE TITLE
bug: flyctl packaging filename change

### ISSUE THREAD

**Issue by chessmango** [chessmango/asdf-flyctl#5]
**Describe the bug**

Between https://github.com/superfly/flyctl/releases/tag/v0.0.513 and https://github.com/superfly/flyctl/releases/tag/v0.0.517, underscore dropped after platform name. Unclear why, as code changes don't imply this necessarily
**Steps to reproduce**

**Expected behavior**

Release filenames should be the same, probably. Though not a given
**Screenshots**

**Additional context**

**Comment by chessmango** [comment]
Raised issue in PR: https://github.com/superfly/flyctl/pull/2074

**Comment by dangra** [comment]
skip that version and bump to https://github.com/superfly/flyctl/releases/tag/v0.0.518

**Comment by chessmango** [comment]
Thanks @dangra! :heart:
