### ISSUE TITLE
Download Fails

### ISSUE THREAD

**Issue by maxexcloo** [chessmango/asdf-flyctl#7]
**Describe the bug**
Using with mise, the download fails (404).

**Steps to reproduce**
```mise use -g flyctl
curl: (22) The requested URL returned error: 404
mise ~/.local/share/mise/plugins/flyctl/bin/download failed
* Downloading flyctl release 2024.6.12-pr3626.3...
curl: (22) The requested URL returned error: 404
asdf-flyctl: Could not download https://github.com/superfly/flyctl/releases/download/v2024.6.12-pr3626.3/flyctl_2024.6.12-pr3626.3_macOS_arm64.tar.gz
mise ~/.local/share/mise/plugins/flyctl/bin/download exited with non-zero status: exit code 1
mise Run with --verbose or MISE_VERBOSE=1 for more information```

**Expected behavior**
Downloads and installs.

**Comment by safinn** [comment]
Use `mise use -g flyctl@0.2.104`.
It's not limited to releases with assets when searching for versions. It fails because the latest tag has no assets.

**Comment by maxexcloo** [comment]
Have been doing this but unfortunately in this situation the auto update doesn’t work - if there’s any way to get it working? Appreciate this plugin by the way, really nice!
